//: Playground - noun: a place where people can play

import UIKit

/**
 Find the Difference
 
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 
 Example:
 
 Input:
 s = "abcd"
 t = "abcde"
 
 Output:
 e
 
 Explanation:
 'e' is the letter that was added.
 **/

class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        var mutableS = s
        for c in t {
            if mutableS.contains(c) {
                mutableS.remove(at: mutableS.index(of: c)!)
            } else {
                return c
            }
        }
        
        return Character.init("")
    }
}
